version: '3.0'
services:
  backend:
    image: golang:1.18.1-buster
    volumes: 
      - ./backend:/opt/app
      - go_root:/go
    environment:
      - PGHOST=manabie-db-1
      - PGUSER=manabie
      - PGDATABASE=manabie
      - PGPASSWORD=manabie
      - SIM_OFFSET_DAY=0
    working_dir: /opt/app
    command: bash -c 'go mod vendor && go install cmd/server.go && server'
    depends_on:
      migrations:
        condition: service_completed_successfully
    ports:
      - 8090:8090
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=manabie
      - POSTGRES_USER=manabie
      - POSTGRES_PASSWORD=manabie
    volumes: 
      - ./db:/var/lib/postgresql/data
  migrations:
    image: node:17-buster-slim
    volumes:
      - ./migrations:/opt/app/workspace
    command: bash -c 'sleep 2 && npx migrate up'
    environment:
      - PGHOST=manabie-db-1
      - PGUSER=manabie
      - PGDATABASE=manabie
      - PGPASSWORD=manabie
      - PGPORT=5432
    working_dir: /opt/app/workspace
    depends_on:
      - db
volumes:
  go_root: